[build]
  # Base directory for the project
  base = "apps/frontend"
  
  # Build command
  command = "npm run build"
  
  # Publish directory
  publish = "apps/frontend/.next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.17.0"
  
  # NPM version
  NPM_VERSION = "9.6.7"

# Redirect rules for SPA
[[redirects]]
  from = "/api/*"
  to = "https://your-railway-backend.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

# Next.js specific settings
[context.production]
  command = "npm run build && npm run export"

[context.production.environment]
  NODE_ENV = "production"