[build]
  # Base directory for the project
  base = "apps/frontend"
  
  # Build command - Next.js 14 with static export
  command = "npm ci && npm run build"
  
  # Publish directory - where static files are generated
  publish = "out"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.17.0"
  
  # NPM version  
  NPM_VERSION = "9.6.7"
  
  # Production environment
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"