[build]
  # Base directory for the project
  base = "apps/frontend"
  
  # Build command - Next.js 14 with static export
  command = "npm ci && npm run build"
  
  # Publish directory - where static files are generated
  publish = "out"

[build.environment]
  # Node.js version - Updated for Prisma compatibility
  NODE_VERSION = "18.20.4"
  
  # NPM version  
  NPM_VERSION = "10.7.0"
  
  # Production environment
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://epiuse-employee-hierarchy-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"