[build]
  # Build command - Next.js 14 with server-side rendering
  command = "npm ci && npm run build"
  
  # Publish directory - Next.js build output for SSR
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.20.4"
  NPM_VERSION = "10.7.0"
  NODE_ENV = "production"

# API proxy to Railway backend
[[redirects]]
  from = "/api/*"
  to = "https://epiuse-employee-hierarchy-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
